### ISSUE TITLE
可不可以简化下后台登录地址呢？

### ISSUE THREAD

**Issue by drny** [zblogcn/zblogphp#102]
1.简化后台登录地址，如http://127.0.0.1/login.php 这样就可以进后台（新用户真的记不住后台名）；
2.能不能在后台增加个修改后台登录地址选项，或者直接修改文件夹名称就达到了修改后台登录地址的目的。

**Comment by zsxsoft** [comment]
不可能

**Comment by ossso** [comment]
可以自己写接口监管，原则上来说，程序不会改这些的；
