### ISSUE TITLE
怎么一直重复安装呀

### ISSUE THREAD

**Issue by cheikh-wang** [zblogcn/zblogphp#103]
最后都提示完成安装了，却又跳转到安装页面

**Comment by ossso** [comment]
检查有没有数据库写入权限，检查文件夹zb_users的权限是否755，检查数据库账户密码等；

**Comment by cheikh-wang** [comment]
我直接给的整个目录777的权限：
chmod -R 777 blog
然后第一次提示安装完成后，数据库里的表也成功创建了的

**Comment by ossso** [comment]
查看一下zb_users/c_option.php文件是否存在呢？不存在，就是配置文件没写入成功，重置一下权限。

**Comment by zsxsoft** [comment]
1. 非BUG建议在论坛提交
2. 自行检查权限配置，若不熟悉命令行可以直接用WinSCP
