### ISSUE TITLE
能出个c_html_css_add.php吗?

### ISSUE THREAD

**Issue by cxgreat2014** [zblogcn/zblogphp#105]
有的话可以设置304缓存, 更好的浏览体验

**Comment by zsxsoft** [comment]
这个是什么？CSS可以直接放.js.php里吧

**Comment by cxgreat2014** [comment]
哈? 前python程序员求教...怎么把css放到c_html_js_add.php里..
我主要是想调用系统提供的插件接口来输出css样式,博客程序既能够简单返回304提升响应速度也能让我的插件目录不暴露出来,大致这样..

**Comment by zsxsoft** [comment]
哦，我看懂你的意思了
你是直接要输出CSS代码是吗
这样的话，c_html_js_add.php可以
```javascript
document.write(`<style>${css}</style>');
```

**Comment by cxgreat2014** [comment]
哦,好的,谢谢
