### ISSUE TITLE
zblog的缓存系统问题导致用户无法获取最新页面

### ISSUE THREAD

**Issue by cxgreat2014** [zblogcn/zblogphp#109]
在我发布文章并修改过之后，zblog依然返回304
![后台](http://p1.bpimg.com/4851/2638d0ef5fe77565.png)
![index](http://p1.bpimg.com/4851/eebac7669cca8661.png)
![request](http://p1.bpimg.com/4851/8ed132fa0ec1c3d1.png)

**Comment by zsxsoft** [comment]
zbp我记得只在html_js_add有304吧，你检查一下你的Apache配置

**Comment by cxgreat2014** [comment]
谜之BUG。。刚刚一度怀疑是PHPStudy=》Apache+PHP5.6n的问题，后来换到笔记本上居然就好了。。现在怀疑可能是模块的问题或者其他程序干扰XXX谜之BUG。。/笑cry，也是没法了
