### ISSUE TITLE
应用中心检测用户是否购买插件函数有错误！

### ISSUE THREAD

**Issue by huisem** [zblogcn/zblogphp#112]
使用
```
$result = AppCentre_App_Check_ISBUY($appid);

if ($result['data']['buy']) {
    echo "已购买插件";
} else {
    $zbp->ShowHint('bad', '您未购买本插件，请到Z-BlogPHP应用中心购买.');
}
```

![qq 20161122151710](https://cloud.githubusercontent.com/assets/4083757/20514429/c3694628-b0c6-11e6-8d67-7a15938c3978.png)

如图提示错误，还有什么时候能把应用中心的API修好？

@involvements

**Comment by rainbowsoft** [comment]
https://wiki.zblogcn.com/doku.php?id=appcenter:verification
函数名不对！

**Comment by huisem** [comment]
@zsxsoft   猪你先检查下应用中心的代码
![qq 20161210233134](https://cloud.githubusercontent.com/assets/4083757/21074307/d4ef88b2-bf30-11e6-9e22-3dd9682adfc9.png)
