### ISSUE TITLE
ZBP检则用户名，规测放宽成什么样？

### ISSUE THREAD

**Issue by rainbowsoft** [zblogcn/zblogphp#117]
ZBP检则用户名，规测放宽成什么样？

**Comment by zsxsoft** [comment]
参照微软的标准的话：


不能包含任何 Unicode 控制字符或代理项字符。
不能包含以下可打印字符：/ : \ ~ & % ; @ ' " ? < > | # $ * } { , + = [ ]
不能包含省略号 (…) 或双句点 (..)
不能包含省略号 (…) 或双句点 (..)
不能以句点 (.) 开头或结束

还要加入全角空格、半角空格、Tab检测

**Comment by zsxsoft** [comment]
用户名不变，但安装时应有检测。
nickname去掉空格的过滤。

**Comment by zsxsoft** [comment]
https://github.com/zblogcn/zblogphp/commit/e6297a919a56c20c30f4e9915f3452398513fd23
https://github.com/zblogcn/zblogphp/commit/f5dd9b24bfb350bd71a10db641d763be7acb2326
