### ISSUE TITLE
sqlpgsql生成语句问题

### ISSUE THREAD

**Issue by rainbowsoft** [zblogcn/zblogphp#121]
$sql = $db ->select("zbp_post")->where(
   array('EXISTS', $db ->select("zbp_post")->where(array('=', 'log_ID', "2"))->sql )
)->sql;
仔细看一下，这个sql里包含了两个sql拼接，其中，后边那个拼接正常，但主sql拼接后，表名不见了！！！
SELECT * FROM WHERE EXISTS ( SELECT * FROM zbp_post WHERE log_ID = '2' )

**Comment by zsxsoft** [comment]
本质上这是Singleton的Racing Condition问题。开发者应该认识到，$zbp->db是一个Singleton，在上面的任何操作都是对同一个实例的更改。要增加一个->new()方法以便子查询的使用。
