### ISSUE TITLE
Z-blog默认编辑器UEditor特殊文件的小图标文件丢失

### ISSUE THREAD

**Issue by workxin** [zblogcn/zblogphp#122]
zb_users/plugin/UEditor/dialogs/attachment/fileTypeImages/*
fileTypeImages文件夹不存在

**Comment by zsxsoft** [comment]
在https://github.com/zblogcn/zblogphp/commit/141f20ff6b7afe8326addce29f872d331b083465与https://github.com/zblogcn/zblogphp/commit/713a928ec478ab5a426296c8fa3d3b192530478b修复。
