### ISSUE TITLE
1.5 下 AddHeaderIcon 失效

### ISSUE THREAD

**Issue by huisem** [zblogcn/zblogphp#124]
1.4
![11](https://cloud.githubusercontent.com/assets/4083757/21752515/981e5b7a-d614-11e6-9a75-747a984af3b1.jpg)

1.5
![22](https://cloud.githubusercontent.com/assets/4083757/21752517/9e5564a2-d614-11e6-8db7-9e586ca47894.jpg)

所有插件添加图标都不显示，不知道是个别情况还是系统bug！

**Comment by huisem** [comment]
@rainbowsoft

**Comment by zsxsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/2398785/21953567/cea6de5a-da75-11e6-865f-45c397de6e56.png)
？？？？？

**Comment by rainbowsoft** [comment]
1.5.1已修；

2017-01-16 10:57 GMT+08:00, zsx <notifications@github.com>:
> Closed #124.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/zblogcn/zblogphp/issues/124#event-923744883


-- 
http://www.rainbowsoft.org/
