### ISSUE TITLE
Open Live Writer支持增强

### ISSUE THREAD

**Issue by zsxsoft** [zblogcn/zblogphp#127]
如题

**Comment by zsxsoft** [comment]
主要问题：
1. 默认主题在Edit模式下的显示问题
2. 预览
3. 
![image](https://cloud.githubusercontent.com/assets/2398785/23329923/b57a2c74-fb7d-11e6-8a05-aa4d75acedde.png)

**Comment by yixiao0307** [comment]
好像只能新增，无法编辑。是我个人设置的问题么？

**Comment by zsxsoft** [comment]
我这里测试是正常的，你描述一下你的情况吧

**Comment by zsxsoft** [comment]
我这里测试是正常的，你描述一下你的情况吧
@yixiao0307

**Comment by zsxsoft** [comment]
算了吧都没人用了
