### ISSUE TITLE
makeleftmenu和maketopmenu增加target参数

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#129]
目前这俩函数生成的菜单都是在当前页面打开的，需要target=“_blank”

**Comment by zsxsoft** [comment]
第二个参数就是target。

**Comment by zsxsoft** [comment]
function MakeTopMenu($requireAction, $strName, $strUrl, $strTarget, $strLiId) {

function MakeSubMenu($strName, $strUrl, $strClass = 'm-left', $strTarget = '', $strId = '', $title = '', $target = '') {
