### ISSUE TITLE
创建c_option.php失败，请创建"网站/zb_system/zb_users/c_option.php

### ISSUE THREAD

**Issue by salikx** [zblogcn/zblogphp#136]
`创建数据库！zblog
连接数据库并创建数据表！
创建并插入数据成功！
创建c_option.php失败，请创建"网站/zb_system/zb_users/c_option.php"文件并将下边的代码复制进文件并保存。
`

实际上应该是"网站/zb_users/c_option.php"才会安装完成，但是安装完又会有新的问题存在。

版本分别是官网的zero和github的都尝试过。

**Comment by zsxsoft** [comment]
你在说什么……

**Comment by salikx** [comment]
安装，第四步出现的问题。

**Comment by zsxsoft** [comment]
仔细阅读了好几遍终于看懂了……

**Comment by involvements** [comment]
已修复，新版发布后更新
