### ISSUE TITLE
发布emoji错误

### ISSUE THREAD

**Issue by involvements** [zblogcn/zblogphp#138]
数据库字段不是utf8mb4情况下发布带emoji表情文章，系统提示发布成功，实际没有发布（mysql插入报错未判断）

**Comment by zsxsoft** [comment]
不科学啊，这里已经自动转换了，你把MySQL的报错提示拿出来看

**Comment by involvements** [comment]
@zsxsoft  类似于：
`#1366 - Incorrect string value: '\xF0\x9F\x91\x88' for column 'tag_Name' at row 1`
