### ISSUE TITLE
同一接口的执行顺序控制

### ISSUE THREAD

**Issue by wdssmq** [zblogcn/zblogphp#145]
https://bbs.zblogcn.com/thread-93711-1-1.html
虽然感觉会很麻烦。。

**Comment by birdol** [comment]
接口就是一个函数的数组而已啊，顺序无非就是数组的排序。。。。

**Comment by wdssmq** [comment]
@birdol 所以说类似z-index那样的实现还是什么？

**Comment by involvements** [comment]
@wdssmq 按照插件管理面板的启用顺序来的，好像asp版本有拖动排序功能，php一直没做

**Comment by wdssmq** [comment]
@involvements 拖动排序这个好像真没有。。

**Comment by involvements** [comment]
@wdssmq 你可以写一下

**Comment by birdol** [comment]
不用拖动排序的吧。
$array1=$GLOBALS['hooks']['Filter_Plugin_Login_Header'];
shuffle($array1)
$GLOBALS['hooks']['Filter_Plugin_Login_Header']=$array1;

**Comment by involvements** [comment]
@birdol 你这是强插了，。。但如果每个插件都这么写呢。。。

**Comment by machealx** [comment]
可以跟wordpress一样的做法啊，就是加个参数，然后机制那里判断一下这个接口有没有加这个参数，如果没加，就给个默认值，如果加了，就看这个参数是多少，比如默认值全是100，然后加了参数99那就让这个参数99的先执行。

**Comment by rainbowsoft** [comment]
关闭，做了等于没做，因为大家都会抢no1

**Comment by involvements** [comment]
@rainbowsoft 你这是偷懒！asp有，php为什么没有！拖动排序

**Comment by zsxsoft** [comment]
哪儿大家都抢了，莫名其妙，你给个低的默认值啊。

**Comment by rainbowsoft** [comment]
这种极少见需求，有需求的自然会实现，没需求的万年用不上！
