### ISSUE TITLE
允许模板更严格的定义自己可以被哪些页面调用

### ISSUE THREAD

**Issue by wdssmq** [zblogcn/zblogphp#146]
{* Template Name: 文章页单页 \*}
{\* Provide To: single|page *}
类似这种感觉。。

**Comment by zsxsoft** [comment]
这个……我个人认为没什么意义吧

**Comment by wdssmq** [comment]
非预定模板默认不列出，除非声明可以列出！
![tim 20170710135952](https://user-images.githubusercontent.com/8186642/28004586-34ba550e-6578-11e7-90e2-254e54adeef5.png)

**Comment by huisem** [comment]
是的！建议不错！分类只显示分类的模板  文章只显示文章的模板   模板多的话 用户傻傻分不清楚！

**Comment by ossso** [comment]
我这个有暴力改过，不过官方能推行一个标准，还是不错的

**Comment by wdssmq** [comment]
或者应该是 Provide For？
杂鱼级别的英语。。总之Just Write This

**Comment by ossso** [comment]
我写了一个json的方式定义。。。

**Comment by rainbowsoft** [comment]
1.6.1.按ossso所说的，用json方式规定自己被哪个调用

**Comment by rainbowsoft** [comment]
1.6.1已增加了type

**Comment by wdssmq** [comment]
求助-论坛事务-ZBlogger技术交流中心
https://bbs.zblogcn.com/thread-103251.html
所以还是上严格白名单吧。。
