### ISSUE TITLE
提倡使用user.StaticName标签

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#152]
为了网站安全性考虑，应该提倡使用user.StaticName标签，主题内评论处调用标签建议全部改成这个，从默认主题做起，引导开发者

**Comment by lanseyujie** [comment]
按照此种思路，登录用户提交评论时是否也应以 StaticName 作为评论者名称为宜呢？这样“评论邮件提醒”之类的插件调用登录用户的评论者名称也会和模板的 user.StaticName 保持一致。
![deepinscreenshot_select-area_20170904114959](https://user-images.githubusercontent.com/16262938/30011278-95561a80-9168-11e7-8c8e-a1ce3f3fda11.png)

**Comment by birdol** [comment]
再加一个，开发者创建应用的时候，应用作者的名字，调用StaticName

**Comment by birdol** [comment]
或者预置一套开发者公开信息，调用也是可以的。
