### ISSUE TITLE
由应用中心在打包时排除指定文件（夹）

### ISSUE THREAD

**Issue by wdssmq** [zblogcn/zblogphp#154]
1、应用目录下的.gitignore识别和解析；
2、应用中心启用开发模式后可以增加配置项，，对新建应用的各字段进行个性化初始；
3、创建应用时可以自动复制指定文件；

**Comment by zsxsoft** [comment]
Relate to: #161 

这些需要进行一并处理

**Comment by zsxsoft** [comment]
https://github.com/zblogcn/zblogphp/commit/4afdd9e227be22391be567ec46532169e2d9fbcb
硬是鸽了这么久

**Comment by wdssmq** [comment]
无论插件是否存在，LoadInfoByXml都会返回$app->id：
https://github.com/zblogcn/zblogphp/commit/4afdd9e227be22391be567ec46532169e2d9fbcb#diff-64b8fad3325d466e549ddd52b9ce16e1R308
