### ISSUE TITLE
GetGuestIP函数的问题

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#156]
通常情况下，GetGuestIP这个函数使用$_SERVER["REMOTE_ADDR"]是正确的。

但是如果网站开启了百度云加速等cdn服务的话，那么$_SERVER["REMOTE_ADDR"]就变成了cdn服务器的IP地址，这时候需要使用$_SERVER["HTTP_X_FORWARDED_FOR"]。

看看怎么破？ 加个接口？ 还是加个开关？

**Comment by zsxsoft** [comment]
嗯，我估计只能这样
