### ISSUE TITLE
x2013 主题内的缩略图名称错误

### ISSUE THREAD

**Issue by lanseyujie** [zblogcn/zblogphp#158]
![_ _20170825193349](https://user-images.githubusercontent.com/16262938/29712420-55674442-89cc-11e7-853b-df7ddb9a07bf.png)
按约定名称应为 screenshot.png

**Comment by involvements** [comment]
该问题已经更新了：https://github.com/zblogcn/zblogphp/commit/a36f2b7dd64b8fe1ce635cef3d5192e440fcd47a
请更新应用后查看
