### ISSUE TITLE
评论 UA 可以储存 js 脚本等无关信息

### ISSUE THREAD

**Issue by lanseyujie** [zblogcn/zblogphp#159]
通过 User-Agent Switcher for Google Chrome 等插件修改 UA ，可以提交含有 js 脚本的 UA 信息，然而并没有太多主题会直接调用评论 UA ...

**Comment by zsxsoft** [comment]
这个没办法啊，所以对于这个你的问题是什么……

**Comment by lanseyujie** [comment]
总感觉这样没有过滤的储存似乎有什么不妥[捂脸]

**Comment by zsxsoft** [comment]
对于可能造成存储型XSS的问题，重要的是在输出前防止问题的出现。对于数据，应当保证它的原汁原味。虽然实际上UA无所谓数据完整性，但出于统一的原则，也这样处理比较合适。

**Comment by pG5heTMrlbBv0mcH** [comment]
这会有存储型XSS的风险的！就算不能对其进行修改，也可以考虑在后台查询时生成为图片格式，防止XSS。在后台出现的XSS是极危险的！我们网站曾经就被后台存储型XSS害死了

**Comment by XAS-712** [comment]
pG5老兄说的很对，但是我认为还是尽量想办法没必要在后台显示的话就不要显示出来，把它base64编个码，老老实实存在数据库里最好，有条件的话可以用用户IP做密钥，AES加密一下，只要同时保存了IP就可以解密，而且还不会出发XSS

**Comment by XAS-712** [comment]
我靠。。。不修复是等着管理员被某个hacker埋的存储型XSS炸弹炸了吗？

**Comment by zsxsoft** [comment]
@pG5heTMrlbBv0mcH @XAS-712 我们后台没有显示UA功能啊？

**Comment by zsxsoft** [comment]
@XAS-712 你的做法对于防范XSS根本没有用处。存储型XSS的触发不在于你在数据库怎么保存，而在于你怎么输出，这不是编码算法或者加密算法能解决的事情。

**Comment by XAS-712** [comment]
不啊，我的意思是尽量需要输出UA的不使用HTML和JS，最好是编译型语言，尽量避免注入

**Comment by XAS-712** [comment]
而如果尝试作为普通文本正常输出就会由于被编码了无法触发

**Comment by XAS-712** [comment]
如果编码后保存不可行可以参考pG5的方法

**Comment by zsxsoft** [comment]
@XAS-712 
User-Agent数据，和一般的数据，如用户评论等，没有任何区别，__都属于用户输入的不可信数据__。这只和你输出的载体有关，如果要输出到HTML，自然就__必须要过滤__，而我们目前没有在任何一个地方输出这些内容。
这和使用的语言没有任何关系。即使是编译型语言，如果我的需求是从用户输入执行代码呢？比如我用C++把用户输入保存成某个文件，再编译这个文件并执行，那我__必然__要对这个程序的危险操作进行拦截。

问题不在于编码后保存不可行，问题在于，__这么做完全没有意义__。

**Comment by ossso** [comment]
楼上两位，对于UA等信息的输出，博士的意思是，需要开发者在输出时进行安全控制；至于编码不编码的问题，假如编码后，每次在数据库直接查看的时候还要解码；这也是很蛋疼的事情。

**Comment by XAS-712** [comment]
哦谢了 @ossso ，我理解了。我语文比较差，不太容易理解一些不是直接指出目的的句子
