### ISSUE TITLE
伪静态url问题

### ISSUE THREAD

**Issue by luckhai** [zblogcn/zblogphp#162]
https://www.songhaifeng.com/ZBlog/3/
https://www.songhaifeng.com/ZBlog/33333333/
ZBlog这个分类下实际上只有3页，为什么访问33333333页还是可以正常打开而不是返回404？

**Comment by zsxsoft** [comment]
陈年老bug

**Comment by birdol** [comment]
广告一下： http://www.birdol.com/zblogphpplugin/fix404.html
------------------ 原始邮件 ------------------
发件人: "老虎会游泳"<notifications@github.com>
发送时间: 2017年9月2日(星期六) 下午2:38
收件人: "zblogcn/zblogphp"<zblogphp@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [zblogcn/zblogphp] 伪静态url问题 (#162)



陈年老bug
 
&mdash;
