### ISSUE TITLE
伪静态的一个坑？

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#164]
页面的伪静态规则 {%host%}{%alias%}/
标签的伪静态规则 {%host%}{%alias%}_{%page%}.html

打开网址 {$host}一个不存在的标签中文名.html

打开的是一个 未命名的 独立页面。

追踪结果。

viewauto

第一次匹配到了tags的规则，转入viewlist $tag

但是在switch($type)

case tag 中

		if (isset($tags['id'])) {
            $tag = $zbp->GetTagByID($tags['id']);
        } else {
            $tag = $zbp->GetTagByAliasOrName($tags['alias']);
 		}

 由于 匹配到的标签不存在，此时$tag没有获取到东西。

 接着

		if ($tag->ID == 0) {//不存在，所以进入
            if ($isrewrite == true) {//开启了伪静态，所以进入
                return false; //返回false
            }

            $zbp->ShowError(2, __FILE__, __LINE__);
        }

回到viewauto

        $r = UrlRule::OutputUrlRegEx($zbp->option['ZC_TAGS_REGEX'], 'tags', false);
        $m = array();
        if (preg_match($r, $url, $m) == 1) {
            isset($m['page']) ? null : $m['page'] = 0;
            $result = ViewList($m['page'], null, null, null, $m, true);
            if ($result == true) {//由于返回了false，所以没能进入这里，而是继续下面的。
                return null;
            }
        }

结果被这里匹配到了。。。

        $r = UrlRule::OutputUrlRegEx($zbp->option['ZC_PAGE_REGEX'], 'page');
        $m = array();
        if (preg_match($r, $url, $m) == 1) {
            $result = ViewPost($m, null, true);
            if ($result == false) {
                $zbp->ShowError(2, __FILE__, __LINE__);
            }

            return null;
        }

我的问题是。。。为啥会被这里匹配到？？？

**Comment by muzikim** [comment]
我来是为了随意说一句无关紧要的话，表示已经发现论坛关闭了。。。

**Comment by zsxsoft** [comment]
@muzikim 很快就会上线的，预计今明两天
