### ISSUE TITLE
开启静态后评论key检验出错

### ISSUE THREAD

**Issue by Pengzf** [zblogcn/zblogphp#165]
form id="frmSumbit" target="_self" method="post" action="http://b.xxx.cn/zb_system/cmd.php?act=cmt&amp;postid=1&amp;key=3bbc86461bbc8ccaad982fca12e20165" >
就是这个from的key检验出错，开启cdn后
因为cdn缓存是2小时，所以评论出现检验码出错，怎么解决

**Comment by zsxsoft** [comment]
这个……有点麻烦，暂时没有好的方案，下个版本处理

**Comment by Pengzf** [comment]
要不评论时候js重写表单action
另外加个key接口php
对整体的性能延迟不大
不然开启cdn了静态页面基本不变
我想不到什么办法了！

**Comment by Pengzf** [comment]
你们的博客不开启cdn?
你怎么解决cdn缓存key问题的！

**Comment by Pengzf** [comment]
c_html_js_add.php
将key变量放在这里，提交表单时获取就行了，cdn不缓存php

**Comment by zsxsoft** [comment]
新版本直接去掉了验证功能
https://github.com/zblogcn/zblogphp/commit/3a5f3d2d23d97fca027466782e8dcf3d327539ec
