### ISSUE TITLE
三个建议

### ISSUE THREAD

**Issue by LoveyCat** [zblogcn/zblogphp#174]
1、文章状态：不支持私有模式，只能是待审核和草稿，然而这个文章我只是想别人看不到，我登录账号后能在文章列表中看到的，希望增加这个功能。
2、附件管理：对比一下WP，他们的附件管理是可以显示出图片缩略图的，这样可以很方便的知道哪些附件我不想要了可以删除，而且还支持批量删除，希望这点也可以优化一下
3、文章管理：不支持批量管理，要想删除只能一篇一篇的删，时间久了，有些文章可能也不想再继续保留了，一篇文章一篇文章的删确实也比较费劲，希望这个功能也可以加上
也许我说的这些功能可以通过插件实现，不过我个人对于插件还是不大喜欢，所以希望这些功能能成为zblog原生的功能，谢谢。

**Comment by zsxsoft** [comment]
1. 这个需求需要，@zxasd
2. 3. 我确认了一下没有免费插件，这样的话我们的确需要考虑一下添加了。

**Comment by oozj** [comment]
前两个的确

**Comment by livepu** [comment]
貌似最新的git beta，还没有这个功能1
功能2有插件实现了。

**Comment by rainbowsoft** [comment]
对于第1点，可以考虑“草稿文章“在个人登录下“前台”可见。
第3点文章管理可以在考虑1.6.1实现

**Comment by rainbowsoft** [comment]
1.6.1已实现文章管理; 私有模式和加锁模式即将可以通过插件实现;
