### ISSUE TITLE
Mebmer牛批

### ISSUE THREAD

**Issue by ossso** [zblogcn/zblogphp#190]
https://github.com/zblogcn/zblogphp/blob/7098aa2e83a7386928d9bccb37f7257dac7c976c/zb_system/function/lib/member.php#L122

**Comment by ossso** [comment]
@rainbowsoft https://github.com/zblogcn/zblogphp/commit/ef18bc57965e4d3cd3071c29c595809e1dab75ba#diff-52237ee920d47dfcb8549be9767ce1b5

**Comment by zsxsoft** [comment]
。。

**Comment by zsxsoft** [comment]
https://github.com/zblogcn/zblogphp/commit/2e2965d0cefa3266190f08cd0e9b3073116d435a
