### ISSUE TITLE
评论回复取消时跳转回原评论？？？？

### ISSUE THREAD

**Issue by wdssmq** [zblogcn/zblogphp#196]
![e p hvnrq_d30 ctet0uv](https://user-images.githubusercontent.com/8186642/44715296-03587c80-aaea-11e8-8799-63ef20145a51.png)

主题自己实现还是系统预置。。果然是好麻烦的问题。。

**Comment by zsxsoft** [comment]
这当然是主题自己实现了啊

**Comment by involvements** [comment]
主题实现
