### ISSUE TITLE
生么情况会触发Undefined index: ZC_MYSQL_ENGINE

### ISSUE THREAD

**Issue by oozj** [zblogcn/zblogphp#197]
ndefined index: ZC_MYSQL_ENGINE报错解决办法
Notice: Undefined index: ZC_DEBUG_MODE in zb_system/defend/error.php on line 33

Undefined index: ZC_MYSQL_ENGINE
可能的错误原因

您在zb_users/c_option.php内配置、或刚才填写的的 MySQL 连接信息是否正确？
您所连接的 MySQL 数据库是否已经成功启动？

如果您是访客，这说明网站程序可能出现了一些错误。请您稍后再试，或联系站长。
如果您是站长，您可以点击【更多信息】来查看Z-Blog官方关于这个错误的说明，也可以到Z-Blog官方论坛，附上错误详细截图与描述寻求帮助。

Notice: Undefined index: ZC_DEBUG_MODE in /zb_system/defend/error.php on line 45

**Comment by zsxsoft** [comment]
当c_option.php不是系统生成的情况下会触发。
