### ISSUE TITLE
CSRF Vulnerability exists in the file of Z-BLOG 1.5.2.1935

### ISSUE THREAD

**Issue by Ppsoft1990** [zblogcn/zblogphp#201]
CSRF Vulnerability exists in the file of Z-BLOG 1.5.2.1935
官网下载的，版本1.5.2.1935
https://www.zblogcn.com/zblogphp/

一些文件可以直接访问会导致csrf_token泄漏。
例如当zb_users/plugin/AppCentre/theme.js.php被以js文件在script标签加载时，
在自己的页面，可以用这个js来操作自己的dom，这样就会间接泄漏csrftoken
![image](https://user-images.githubusercontent.com/43659930/47644006-fcacbb00-dba7-11e8-8e47-f91634ab640f.png)

同时后端对新建模版、新建插件正则似乎有点小问题。最终可能导致代码执行。
![image](https://user-images.githubusercontent.com/43659930/47644173-64fb9c80-dba8-11e8-8dda-557eb3f4f3c6.png)
[CSRF Vulnerability exists in the file of Z-BLOG 1.5.2.1935.docx](https://github.com/zblogcn/zblogphp/files/2524853/CSRF.Vulnerability.exists.in.the.file.of.Z-BLOG.1.5.2.1935.docx)

**Comment by zsxsoft** [comment]
1. CSRF Token泄漏问题收到，非常感谢！
2. 后台本身就可代码执行，除非开启应用中心的“安全模式”。不过这个正则的确有毒……

**Comment by zsxsoft** [comment]
2018-12-19，常规更新修复。非常感谢。
