### ISSUE TITLE
PHP7.3 应用中心报错

### ISSUE THREAD

**Issue by involvements** [zblogcn/zblogphp#203]
![image](https://user-images.githubusercontent.com/1711966/51227565-f43a7400-198f-11e9-80d2-d4ccefee44a2.png)
(2)E_WARNING : "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? (set_error_handler) (2.0.0.1910 (Beta)) (WINNT; nginx1.13.5; PHP 7.3.0 x64; mysqli; curl)

https://wiki.php.net/rfc/continue_on_switch_deprecation

**Comment by zsxsoft** [comment]
早修了
