### ISSUE TITLE
File upload Bug

### ISSUE THREAD

**Issue by lj1025676027** [zblogcn/zblogphp#213]
http://127.0.0.1/zblogphp/zb_users/plugin/ueditor/dialogs/scrawl/scrawl.php ,This page allows visitors to upload files to the server. Various web applications allow users to upload files (such as pictures, images, sounds, ...). Uploaded files may pose a significant risk if not handled correctly. A remote attacker could send a multipart/form-data POST request with a specially-crafted filename or mime type and execute arbitrary code.
Form name: <empty>
Form action: http://127.0.0.1/zblogphp/zb_users/plugin/ueditor/dialogs/scrawl/scrawl.php
Form method: POST
Form inputs:upfile [File]

**Comment by zsxsoft** [comment]
https://github.com/zblogcn/zblogphp/blob/master/zb_users/plugin/UEditor/dialogs/scrawl/scrawl.php
No PHP codes here, no one can upload through this file.

**Comment by zsxsoft** [comment]
https://github.com/zblogcn/zblogphp/blob/master/zb_users/plugin/UEditor/dialogs/scrawl/scrawl.php
No PHP code in this file.
