### ISSUE TITLE
User credentials are sent in clear text

### ISSUE THREAD

**Issue by lj1025676027** [zblogcn/zblogphp#214]
User credentials are transmitted over an unencrypted channel. This information should always be transferred via an encrypted channel (HTTPS) to avoid being intercepted by malicious users.A third party may be able to read the user credentials by intercepting an unencrypted HTTP connection.
Form name: <empty>
Form action: http://127.0.0.1/zblogphp/zb_system/login.php
Form method: POST

**Comment by zsxsoft** [comment]
No password is hashed.

**Comment by CHYbeta** [comment]
观光
