### ISSUE TITLE
Z-BlogPHP 1.5.2  Open redirect vulnerability

### ISSUE THREAD

**Issue by github123abc123** [zblogcn/zblogphp#216]
Z-BlogPHP 1.5.2 has an Open Redirect via the zb_system/cmd.php redirect parameter.
Open Redirection vulnerability Technical details:
URL : http://localhost/zblog/zb_system/cmd.php?atc=login&redirect=http://www.baidu.com
code:
case 'login':
        if (!empty($zbp->user->ID) && GetVars('redirect', 'GET')) {
            Redirect(GetVars('redirect', 'GET'));
        }
        if ($zbp->CheckRights('admin')) {
            Redirect('cmd.php?act=admin');
        }
        if (empty($zbp->user->ID) && GetVars('redirect', 'GET')) {
            setcookie("redirect", GetVars('redirect', 'GET'), 0, $zbp->cookiespath);
        }
        Redirect('login.php');
        break;

First: You need login in,then the vulnerability can run.So we use vulnerability for phishing attacks.
Parameter Name : redirect
Parameter Type : GET
Attack Pattern : http://www.baidu.com

(auth:1521106949@qq.com)

Should there be anything else we can help you with, please do not hesitate to ask.

**Comment by zsxsoft** [comment]
Duplicated with #209 
https://github.com/zblogcn/zblogphp/commit/0071602517c6d6eb39db1e556ab42992a7595863

**Comment by zsxsoft** [comment]
还有我求求你们了用中文好不好，你们刷CVE的这些人要么百度翻译，要么写的英语谁都看不懂。
