### ISSUE TITLE
很久没推送大版本升级了，难道直接git获取？

### ISSUE THREAD

**Issue by livepu** [zblogcn/zblogphp#217]
官网下载的版本很老了，不知道有没有大版本推送呢？

**Comment by zsxsoft** [comment]
我们会在新的默认主题设计完成之后准备发布新版本。

**Comment by livepu** [comment]
加油，老大。期待啊。另外，我觉得可以参考下icms的升级方法，可以选择git更新或者稳定版更新。挺好的。

**Comment by zsxsoft** [comment]
Git更新主要是大部分主机都缺少运行``git``命令的权限，所以说还是有点麻烦的

**Comment by praming** [comment]
> 我们会在新的默认主题设计完成之后准备发布新版本。

3个月过去了，大概什么时间可以发布新版呢？等不及了啊。

**Comment by zsxsoft** [comment]
@praming 新设计还在🕊️中。。。。

**Comment by praming** [comment]
> @praming 新设计还在🕊️中。。。。

不要新设计了，随便弄个默认主题先发布出来，先来个预览版，反正到手主题还要自己写。

**Comment by zsxsoft** [comment]
@praming 那你可以直接从GitHub拿嘛

**Comment by praming** [comment]
@zsxsoft GitHub已经是全新版本了吗？

**Comment by zsxsoft** [comment]
@praming 我们一直是按照开源软件的模式开发，GitHub上就是最新的版本

**Comment by livepu** [comment]
git 上获取的没有应用中心这个功能。
