### ISSUE TITLE
 zblog sqlite版本 更改 数据库存放位置

### ISSUE THREAD

**Issue by vjsdhyygy** [zblogcn/zblogphp#220]
如题 ，是存放在 data 目录下，
我想 移动到网站根目录以外的地方 ，在配置中，貌似只能存放在data 目录下，或者有变更的地方，不好找的说 。
  变更那个文件的那个目录？

**Comment by zsxsoft** [comment]
zb_users/c_option.php 可直接修改

**Comment by vjsdhyygy** [comment]
```
return array (
  'ZC_CLOSE_WHOLE_SITE' => false,
  'ZC_DATABASE_TYPE' => 'sqlite3',
  'ZC_SQLITE_NAME' => '#%数据库名字.db',
  'ZC_SQLITE_PRE' => 'zbp_',
  'ZC_MYSQL_SERVER' => 'localhost',
  'ZC_MYSQL_USERNAME' => 'root',
  'ZC_MYSQL_PASSWORD' => '',

```

这里只有修改数据库的名字的说 。。。。。。

**Comment by zsxsoft** [comment]
``  'ZC_SQLITE_NAME' => '#%数据库名字.db',``

改成比如
``  'ZC_SQLITE_NAME' => '/var/lib/your_website/your_database.db',``

等路径就ok了
