### ISSUE TITLE
后台文章编辑的“用户选择”使用ajax的搜索框会更好？

### ISSUE THREAD

**Issue by zhouzishu** [zblogcn/zblogphp#223]
在用户太多的时候，select显得很……
搞成带ajax搜索的会更好？

参考（远程搜索Select）：
https://select2.org/
https://element.eleme.cn/#/zh-CN/component/select

**Comment by zsxsoft** [comment]
来PR啊（

**Comment by zhouzishu** [comment]
引用个jq库select2是否可以？

**Comment by zhouzishu** [comment]
好吧我看看用jq写个
