### ISSUE TITLE
自带编辑器，插入音乐、视频的代码很老

### ISSUE THREAD

**Issue by livepu** [zblogcn/zblogphp#226]
能否更新下编辑器呢，已经很旧了。

**Comment by zsxsoft** [comment]
UEditor的话基本不更新了，但是基于插件兼容性的缘故我不能把编辑器更换为别的，因此基本无解。。

**Comment by zsxsoft** [comment]
已更新UEditor版本

1. 图片搜索因接口失效已去除
2. 插入音乐已去除
3. 百度地图接口已修复
4. 视频：移除Flash的embed代码，外站视频全部转为iframe
5. 视频：支持优酷、腾讯视频、Bilibili、AcFun、YouTube的地址直接插入，支持爱奇艺、搜狐视频的分享地址提示
