### ISSUE TITLE
GetPost函数获取的对象是保护的

### ISSUE THREAD

**Issue by livepu** [zblogcn/zblogphp#228]
我按照这个文章
https://wiki.zblogcn.com/doku.php?id=zblogphp:development:functions:getpost
调用GetPost后，发现Title，是在data对象里面，但这个data是被保护的。
按wiki的方法无法调用。

**Comment by zhouzishu** [comment]
显然 $data 是 protected 的……

但是你有没有注意到有个 __get 魔术方法，你可以直接 $post->Title 来调用的。

**Comment by livepu** [comment]
我测试的是后台插件调用，按wiki方法确实不行，按照你的方法确实可以哦。
后来再测试模板的显示，却可以按照wiki来实现。

**Comment by zhouzishu** [comment]
这么说吧，模板中的 {{ $post.Title }} 会自动编译成 $post->Title 的，模板引擎为了方便特地这么做的。

**Comment by zhouzishu** [comment]
另外，建议先看看 php 无法，默认的 . 是用来连接字符串的。
调用对象中的方法和变量应该用的是 ->
