### ISSUE TITLE
SQLite3::query(): Unable to prepare statement: 1, no such column: cate_Type

### ISSUE THREAD

**Issue by vitoland** [zblogcn/zblogphp#229]
`SQLite3::query(): Unable to prepare statement: 1, no such column: cate_Type`
新建文章和删除文章时会弹出这个提示
文章状态是新建成功和删除成功
修改文章没有这个提示 状态是修改成功
版本就是发issues时最新的

**Comment by vitoland** [comment]
一个应用发布时是免费的，后来收费了。
后台有更新提示，点击更新会更新失败。
此时页面空白
控制台显示 `method=down
id=1859
token=618a94f691213382052c532408cf9608
_=1565280719400` 500错误

**Comment by zhouzishu** [comment]
`cate_Type` 估计是版本的冲突，目前官方发布的正式版中的分类数据表未含有 `cate_Type` 字段，Git 上的开发版是存在的。
发布时免费的，后来收费了，是要购买了才能更新的。

**Comment by zsxsoft** [comment]
cate_Type是因为在GitHub里没发布

应用更新这个问题我们会进行提示优化
