### ISSUE TITLE
windows kangle 环境下 开启SSL并后台固定域名重定向循环bug

### ISSUE THREAD

**Issue by fytowin** [zblogcn/zblogphp#230]
已知kangle兼容apache伪静态规则。
windows下部署kangle运行环境并部署SSL证书开启https访问。
登录后台固定链接为https://xxxx.com，静态化管理中心开启伪静态并部署.htaccess后，出现bug。
访问zblog除首页正常，其他页面https访问后出现“此网页包含过多的重定向”的错误。
windows下apache环境没有此类问题出现，只发现kangle环境与系统存在兼容性。

**Comment by birdol** [comment]
没必要  kangle问题可不止这一个，要兼容起来累死人了。

**Comment by rainbowsoft** [comment]
小众问题，关闭！
