### ISSUE TITLE
开启拦截第三方cookie后，应用中心评论出错。

### ISSUE THREAD

**Issue by vitoland** [zblogcn/zblogphp#231]
提交时弹出的错误提示为404。
是否考虑处理一下。

**Comment by zsxsoft** [comment]
你在说啥

**Comment by vitoland** [comment]
是应用中心的相关问题。
大概就是，浏览器比如firefox开启了拦截所有第三方cookie，在应用中心对主题或插件提交评论的时候，评论会失败，弹出的错误是404。以前一直不知道为啥，今天突然想到一直都开启了拦截所有第三方cookie，才发现是这个原因。
当然，应该没太多人开启这个，所以，也不知道算不算小bug。。。

**Comment by zsxsoft** [comment]
这个也没法修啊。。。只能考虑友好化一下了

**Comment by rainbowsoft** [comment]
这个是用户操作问题，关掉。理论上所有的需要验证的网站全站是依赖cookie的！
