### ISSUE TITLE
base数据操作基类是否考虑多添加几个方法

### ISSUE THREAD

**Issue by Song-HaiFeng** [zblogcn/zblogphp#232]
从中发现 LoadInfoByID 和 LoadInfoByField
其中ByID就不说了，ByField还不支持数组。
例如我只想查（多条件）单条数据只能Query后[0]，这样太难受了啊。
还是说有方案但我没有get到？
所以说，基础的CRUD能不能多添加几个方法呢？

**Comment by birdol** [comment]
虽然官方已经改了，但是还是要说LoadInfoByAssoc就可以查数组。另外可以自己扩展之后增加需要的，比如loadinfobydoublefield。。。
