### ISSUE TITLE
最新的稳定版1.5.1.1740 上有没有漏洞？？

### ISSUE THREAD

**Issue by xadf-xadf** [zblogcn/zblogphp#241]
最新的稳定版1.5.1.1740是在2017年发布的 

有个漏洞是2018年发现和修复的

那最新的稳定版 上 是修复了呢 还是一直是未修复的状态

**Comment by zsxsoft** [comment]
严重的漏洞我们早已更新安装包，且后台应用中心也可以直接升级。基本上你可以认为管理员密码不泄漏的话就不会对你造成影响。
