### ISSUE TITLE
php7.1+切换主题报错

### ISSUE THREAD

**Issue by zpanz** [zblogcn/zblogphp#244]
php7.1（含）以上版本后台切换主题会报错。A non-numeric value encountered

**Comment by zsxsoft** [comment]
没有出现此类问题，能否打开开发模式后提供详细的信息？

**Comment by zpanz** [comment]
错误信息

(8)E_NOTICE : Undefined property: App::$sidebars_sidebar6 (set_error_handler) (1.6.0.2000 (Beta)) (WINNT; Apache2.4.39; PHP 7.1.30 x64; mysqli; curl)
文件位置

H:\SS\zb_system\function\c_system_event.php
2902	
2903	$oldtheme = $zbp->option['ZC_BLOG_THEME'];
2904	
2905	if ($oldtheme != $theme) {
2906	if ($app->sidebars_sidebar1 | $app->sidebars_sidebar2 | $app->sidebars_sidebar3 | $app->sidebars_sidebar4 | $app->sidebars_sidebar5 | $app->sidebars_sidebar6 | $app->sidebars_sidebar7 | $app->sidebars_sidebar8 | $app->sidebars_sidebar9) {
2907	$s1 = $zbp->option['ZC_SIDEBAR_ORDER'];
2908	$s2 = $zbp->option['ZC_SIDEBAR2_ORDER'];
2909	$s3 = $zbp->option['ZC_SIDEBAR3_ORDER'];
2910	$s4 = $zbp->option['ZC_SIDEBAR4_ORDER'];
2911	$s5 = $zbp->option['ZC_SIDEBAR5_ORDER'];
堆栈跟踪

4	H:\SS\zb_system\cmd.php
( 353) SetTheme(0 => clear,1 => default,)
$install .= SetTheme(GetVars('theme', 'POST'), GetVars('style', 'POST'));
请求数据

$%_GET = Array
(
    [act] => ThemeSet
)
$%_POST = Array
(
    [csrfToken] => f8fe73c802d637cf15f158d4cbe60a43
    [theme] => clear
    [style] => default
)
$%_COOKIE = Array
(
    [timezone] => 8
    [addinfo] => {"chkadmin":1,"chkarticle":1,"levelname":"\u7ba1\u7406\u5458","userid":"1","useralias":"\u9694\u58c1\u8001\u674e"}
)
引用文件

0	H:\SS\zb_system\cmd.php
1	H:\SS\zb_system\function\c_system_base.php
2	H:\SS\zb_system\function\c_system_version.php
3	H:\SS\zb_system\function\c_system_compat.php
4	H:\SS\zb_system\function\c_system_plugin.php
5	H:\SS\zb_system\function\c_system_debug.php
6	H:\SS\zb_system\function\c_system_common.php
7	H:\SS\zb_system\function\c_system_event.php
8	H:\SS\zb_system\defend\option.php
9	H:\SS\zb_users\c_option.php
10	H:\SS\zb_system\function\lib\zblogphp.php
11	H:\SS\zb_system\function\lib\dbsql.php
12	H:\SS\zb_system\function\lib\config.php
13	H:\SS\zb_system\function\lib\metas.php
14	H:\SS\zb_users\language\zh-cn.php
15	H:\SS\zb_system\function\lib\database\mysqli.php
16	H:\SS\zb_system\function\lib\database\interface.php
17	H:\SS\zb_system\function\lib\sql\mysql.php
18	H:\SS\zb_system\function\lib\sql\global.php
19	H:\SS\zb_users\theme\nhlsj\include.php
20	H:\SS\zb_users\plugin\AppCentre\include.php
21	H:\SS\zb_users\plugin\IMAGE\include.php
22	H:\SS\zb_users\plugin\IMAGE\thumbHander.php
23	H:\SS\zb_users\plugin\IMAGE\IMAGE.php
24	H:\SS\zb_users\plugin\STACentre\include.php
25	H:\SS\zb_users\plugin\Totoro\include.php
26	H:\SS\zb_users\plugin\Neditor\include.php
27	H:\SS\zb_users\plugin\AppCentre\language\zh-cn.php
28	H:\SS\zb_system\function\lib\member.php
29	H:\SS\zb_system\function\lib\base.php
30	H:\SS\zb_system\function\lib\category.php
31	H:\SS\zb_system\function\lib\module.php
32	H:\SS\zb_system\function\lib\modulebuilder.php
33	H:\SS\zb_system\function\lib\template.php
34	H:\SS\zb_system\function\lib\app.php
35	H:\SS\zb_system\defend\error.php
36	H:\SS\zb_system\function\lib\xsshtml.php
37	H:\SS\zb_system\function\lib\network.php
38	H:\SS\zb_system\function\lib\network\curl.php
39	H:\SS\zb_system\function\lib\network\interface.php

**Comment by zsxsoft** [comment]
应该是 https://github.com/zblogcn/zblogphp/commit/24a1af2c25ba341e7086db325452929069feb8a3 引起的问题，感谢
