### ISSUE TITLE
后台顶部导航样式建议

### ISSUE THREAD

**Issue by kfuudotcn** [zblogcn/zblogphp#256]
顶部的导航，当前页和非当前页，没选中的暗一点就行了，选中的还是白底，目前只是加不加粗的区别。未选中的底色，还是跟.SubMenu a底色相同。
这样更能突出当前位置

**Comment by rainbowsoft** [comment]
依据花晨月夕的建议修改了后台顶部菜单的背景色，已解决，关闭！
