### ISSUE TITLE
可以在创建表时备注字段

### ISSUE THREAD

**Issue by kfuudotcn** [zblogcn/zblogphp#257]
像这样的
        $zbp->datainfo['mdt_order'] = array(
            'ID'            => array('odr_ID','integer','',0),   
            'UID'           => array('odr_UID','integer','',0,'用户ID'),  
            'Time'          => array('odr_Time','integer','',0,'创建订单时间'), 
            'Status'        => array('odr_Status','integer','',0,'订单状态'), 
        );

**Comment by rainbowsoft** [comment]
关闭，已提交实现！
