### ISSUE TITLE
zblog 伪静态支持插件。规则的BUG

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#26]
假设博客地址http://www.baidu.com/
如果首页设置成
{%host%}index_{%page%}.html   
那么首页是
http://www.baidu.com/
分页是http://www.baidu.com/index_2.html   
这样是没错的。

但是如果分类设置成
{%host%}{%alias%}/index_{%page%}.html
分类的首页变成了...
http://www.baidu.com/fenlei1/index_.html
我希望分类分页的地址是
http://www.baidu.com/fenlei1/index_2.html
这种。

**Comment by zsxsoft** [comment]
你这特么怎么做到？！
