### ISSUE TITLE
为啥英文标点符号都变成了中文标点符号？

### ISSUE THREAD

**Issue by super-vip** [zblogcn/zblogphp#261]
不管是复制粘贴的还是手打的代码、文字之类的，在前端页面打开时会自动转换成中文标点符号，这很烦啊……
我记得z-blog以前没这问题啊，有这问题的是wordpress。求解！

**Comment by zsxsoft** [comment]
没懂你在说什么

**Comment by super-vip** [comment]
写文章 粘贴的代码 是英文的标点符号 编辑页面正常 但是在非编辑页面查看就变成中文标点符号 例如英文的 ' 和 " 标点符号自动变成了中文的 ‘ “

**Comment by zsxsoft** [comment]
没有这个问题，例如这些文章即为英文标点符号
https://blog.zblogcn.com/2020/04/21/108/
https://app.zblogcn.com/?id=6951

**Comment by super-vip** [comment]
![image](https://user-images.githubusercontent.com/19517568/81207410-167e5800-9000-11ea-8c6a-df47335d84f6.png)

**Comment by rainbowsoft** [comment]
没有这回事，我特地装了一个1.6.0验证过的。你关掉你所有的插件和切换回默认主题，再测试一下。然后找出是哪个插件的问题！

**Comment by super-vip** [comment]
再次检查了，确定只开启了默认主题，未开启任何插件。确实没找到是什么原因导致的。
![image](https://user-images.githubusercontent.com/19517568/81260150-043a0380-906c-11ea-8e20-5fb9ba264b40.png)
![image](https://user-images.githubusercontent.com/19517568/81260189-1451e300-906c-11ea-923a-8d96d7ef733f.png)

**Comment by zsxsoft** [comment]
检查是否有防火墙、WAF等安全保护措施。
