### ISSUE TITLE
Module management - new module functionality has storage XSS vulnerabilities

### ISSUE THREAD

**Issue by caitoubu** [zblogcn/zblogphp#262]
Click the new module in the module management module, and enter Payload: in the title. Js code inside the module can be executed after saving the module.
![image](https://user-images.githubusercontent.com/65132782/81853624-3cbb6f00-958f-11ea-925b-e342620a0ea6.png)

**Comment by zsxsoft** [comment]
先搞懂漏洞的定义是什么，再来挖漏洞吧。
别看了什么挖CVE教程就来骗CVE了，还不如去做几道CTF题。
