### ISSUE TITLE
希望有统一的注册方法

### ISSUE THREAD

**Issue by kfuudotcn** [zblogcn/zblogphp#265]
应用中心现在各种用户中心、登录注册插件层出不穷，有的网站会同时用2种插件或者主题来注册账号。
要各个主题或者插件之间都能相互兼容是不可能的，比如用**A**插件来注册，到另一个**B**插件的页面下，可能就会缺少用户配置数据而错误，这种数据只有会在注册的时候产生，那用其它插件去注册，就不好再去生成这些数据了。
再比如，某个用户中心插件需要强制使用邀请码才可以注册，但是网站还有用其它登录注册插件却可以直接注册成功。虽然说不好做到插件之间来共享（或兼容）注册时的文本框，但后端注册是可以统一，这样缺少某些数据时可以提示给用户。

可以新增一个函数专门用来注册？里面加上钩子？

**Comment by kfuudotcn** [comment]
如果可以的话，登录方法也可以统一一下。

**Comment by rainbowsoft** [comment]
先看看，南望王师又一年。。。

**Comment by zsxsoft** [comment]
注册和登录本身就是系统统一的接口，邀请码之类的功能系统不提供，本就是插件各自提供的功能。我不太懂你的需求是什么。

**Comment by zsxsoft** [comment]
如果是说需要提供统一的规范的话不合适，主要是你为什么要启用多个注册插件呢？

**Comment by kfuudotcn** [comment]
> 如果是说需要提供统一的规范的话不合适，主要是你为什么要启用多个注册插件呢？

不是我要启用多个注册插件，我也管不了这么用户让他只能用一个注册插件啊。

**Comment by kfuudotcn** [comment]
> 注册和登录本身就是系统统一的接口，邀请码之类的功能系统不提供，本就是插件各自提供的功能。我不太懂你的需求是什么。
意思就是用其中一个插件注册提交的时候，其它插件也能介入处理一些数据。
邀请码之类的我只是来举例说明这个事情。
登录应该是有的，但是我发现有的主题或者插件没用veirfylogin那个函数。
但是注册，你说的注册要么就是postmember这个函数？这个用起来真的很费劲，还要额外的写很多代码，我新插件已经放弃使用这个函数来注册了。

**Comment by kfuudotcn** [comment]
我觉得登录verifylogin这个函数里，应该在验证密码成功后，在设置cookie前加个钩子，因为某些情况下其它插件不允许这个用户登录，这样在登录过程中就可以拦截。

**Comment by rainbowsoft** [comment]
本次讨论已关。说个重点：
**要替换系统的流程，那系统的接口也要捎带上**

**Comment by rainbowsoft** [comment]
原则1：
插件的命名和位置要对应相符
原则2：
要替换系统的流程，那系统的接口也要捎带上

收工！！！ @kfuudotcn
