### ISSUE TITLE
hint_always并没有使用的时机？？

### ISSUE THREAD

**Issue by wdssmq** [zblogcn/zblogphp#274]
需要在AutoHideTips执行前加上这个类名，但是ＰＨＰ和JS都没有给机会

**Comment by wdssmq** [comment]
好吧。。目测要这样用
`$zbp->SetHint("tips hint_always","提示信息")`

函数定义的地方加个说明？

**Comment by rainbowsoft** [comment]
是的，不过1.7不用这样设置了，1.7的$zbp->SetHint加增显示时间的参数，设为10000秒，就差不多和hint_always一个效果了。
