### ISSUE TITLE
$zbp->GetModuleByFileName()方法不能返回模块实例。

### ISSUE THREAD

**Issue by libasten** [zblogcn/zblogphp#280]
在插件开发时候发现这这样的问题。
```
global $zbp;
$moduleExist = $zbp->GetModuleByFileName('navbar');
// $moduleExist = $zbp->GetModuleByID(1);
var_dump($moduleExist->Content);
````
系统安装后，navbar这个模块的id是1，如果通过上面的GetModuleByFileName('navbar')去查询对象实体，无法获得内容。
如果通过下面的$zbp->GetModuleByID(1)则能正常返回。

**Comment by rainbowsoft** [comment]
实测，1.6.6下，$zbp->GetModuleByFileName('navbar')正常的！
