### ISSUE TITLE
别名是否存在逻辑冲突问题

### ISSUE THREAD

**Issue by mos1128** [zblogcn/zblogphp#281]
在管理后台对用户的编辑并没有对别名要求唯一性，两个账号别名都可以为aaa。
但在未登录想要评论时输入已有别名aaa则会提示请勿冒名顶替，是否存在逻辑冲突问题。
最近做插件遇到了这个事情，想听下官方的看法，还是说逻辑上应该保持别名的唯一性。

**Comment by zhouzishu** [comment]
https://github.com/zblogcn/zblogphp/commit/0c95b981135f02b6fd2ae8f759feebd799493621
不查别名了
