### ISSUE TITLE
文章管理页，502 Bad Gateway

### ISSUE THREAD

**Issue by livepu** [zblogcn/zblogphp#283]
宝塔的php8 
当前版本1.6.6.2150 (Valyria); AppCentre2.57
其他页面都正常访问的，就是这个页面提示502.不知道有什么影响了。

插件就几个，很常规。
拓源纯净主题 3.2 | TOYEAN | 2021-01-01 |  
应用中心客户端 2.57 | zx.asd | 2020-12-07 |  
UEditor编辑器 1.6.5 | zsx | 2020-11-13 |  
Totoro - 评论审核系统 2.6 | zsx | 2020-05-01 |  
静态管理中心 1.4 | zx.asd | 2019-12-25 |  
图式附件管理 1.3 | 尔今 | 2020-03-17 |  
阿里云OSS - Free 1.1 | 橙色阳光 | 2019-03-11 |  
输入密码可见内容 1.1 | 菜仔卢 | 2019-05-07 |  
页内href=指定文章 1.1 | food | 2019-08-21 |  
Gravatar头像 1.4

**Comment by zhouzishu** [comment]
目测非程序本身 BUG，请前往 ZBlogger 论坛交流，附上具体信息。
