### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by moeshin** [zblogcn/zblogphp#290]
php: v8.0.2
zblog: 1.7.0.2800 (Beta)

**Comment by moeshin** [comment]
现在只能用这个 nologin.php 登录，重置密码也不行

https://bbs.zblogcn.com/thread-83419.html

**Comment by moeshin** [comment]
新建的站，现在把数据库清了重装就好了，怪异:joy:

**Comment by zhouzishu** [comment]
此类问题以后请到论坛提问
