### ISSUE TITLE
Object of class Database__MySQLi could not be converted to string

### ISSUE THREAD

**Issue by RiotGamesU** [zblogcn/zblogphp#296]
win10 latest + apache2.4或nginx1.19.7+phpnts8.0.3+mysql8.0.3,安装步骤到第四步是报此错误,表存储引擎和数据库驱动都切换第一个选项试过,会报其他错

**Comment by rainbowsoft** [comment]
你试一下，最新的1.7 Beta，还出错吗？

**Comment by rainbowsoft** [comment]
我在php8.0下测过MySQLi安装，没毛病的！
