### ISSUE TITLE
使用z-blog新建文章时出现错误

### ISSUE THREAD

**Issue by dingpengyu** [zblogcn/zblogphp#300]
服务器系统信息：
操作系统： ubuntu 20.04 lts
网站环境： oneinstack最新测试版
php版本： 8.0.3
数据库： maria db 最新版
网站服务器： nginx最新稳定版
错误信息如下： 
Error
edit.php:1 链接
Unchecked runtime.lastError: The message port closed before a response was received.
Warning
DevTools failed to load source map: Could not load content for
chrome-extension://kjahokgdcbohofgdidndeiaigkehdjdc/vendor/js/browser-polyfill.js.map 链接
: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
edit.php:1
 
Unchecked runtime.lastError: The message port closed before a response was received.
DevTools failed to load source map: Could not load content for 
chrome-extension://kjahokgdcbohofgdidndeiaigkehdjdc/vendor/js/browser-polyfill.js.map
: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
Console prompt
​

重现方式：
z-blog后台/新建文章
打开chrome菜单-更多工具/开发者工具
即可重现错误

**Comment by dingpengyu** [comment]
z-blog版本：
最新稳定版。

**Comment by zsxsoft** [comment]
这几个是你浏览器扩展的错误，不是程序的错误
