### ISSUE TITLE
安装卡在step=2，勾选协议后无法继续

### ISSUE THREAD

**Issue by YYago** [zblogcn/zblogphp#302]
```
[Violation]Parser was blocked due to document.write(<script>)
a @ common.js?172945:1
(匿名) @ common.js?172945:1
(匿名) @ common.js?172945:1
```
zblogphp Tenet

(应该是Apache，具体版本未知) ;PHP 7.2 ; MySQL 5.7；有 **SSL**(难道是问题所在……)

阿里虚拟主机，权限也就那么点。web root 权限已全部755.

好像是加载 JS 失败，应该不是什么大问题，但问题是无法继续安装……断点停在 JQuery上……反正是搞不定了

**Comment by rainbowsoft** [comment]
换浏览器.
