### ISSUE TITLE
1.7缩略图改进建议2

### ISSUE THREAD

**Issue by wzgbwxl** [zblogcn/zblogphp#307]
Thumbs 加个新参数？如果true则原比例生成，此时$width与$height的值为最大宽度和最大高度。
Thumb::Thumbs是否增加判断，如果传入不支持的后缀则返回原url
AllImages包含了所有图片，Thumbs只会生成特定后缀，有没有必要改一下？个人倾向于保持现状，由开发者自行判断。

**Comment by wzgbwxl** [comment]
第三条建议取消，AllImages不做限制，自行判断比较好。

**Comment by wzgbwxl** [comment]
又想起一个，相对地址生成失败问题需要修一下

**Comment by zhouzishu** [comment]
相对地址生成失败已修
https://github.com/zblogcn/zblogphp/commit/32a29614151fc0f81db9743372fac37e8b8d25e5
其他暂不考虑
