### ISSUE TITLE
算是bug吧？host若发生变化则重新生成了一遍新的缩略图

### ISSUE THREAD

**Issue by wzgbwxl** [zblogcn/zblogphp#311]
比如http和https下的缩略图是不一样的
比如网站绑了多个域名，thumbs下会出现大量重复的缩略图
这个不太合理...

**Comment by zhouzishu** [comment]
已修
https://github.com/zblogcn/zblogphp/commit/1eb1b9325896de8d15f359e6e0826695d12397f0

**Comment by zhouzishu** [comment]
https://github.com/zblogcn/zblogphp/commit/4f36e7a85b777da52c9f05dff903c0e746759825
