### ISSUE TITLE
脚本入口控制要加严

### ISSUE THREAD

**Issue by hkargv** [zblogcn/zblogphp#324]
假如恶意用户直接访问: http://***.com/zb_users/plugin/AppCentre/include.php 
服务器没有配置好的话会暴露出一些信息 Fatal error: Uncaught Error: Call to undefined function RegisterPlugin() in...
不知道有没有安全风险

特别是第三方插件,几乎都有这个问题

**Comment by rainbowsoft** [comment]
可以加入
if (!defined('ZBP_PATH')) {
    exit('Access denied');
}
