### ISSUE TITLE
建议为MariaDB加上Aria引擎选项

### ISSUE THREAD

**Issue by hkargv** [zblogcn/zblogphp#325]
MariaDB默认也是MyISAM引擎，表损坏比较常见，建议默认用Aria
当然这算是小众需求了

**Comment by rainbowsoft** [comment]
1.7.3可以考虑加入;

**Comment by rainbowsoft** [comment]
在安装页，可以用Chorme修改一下select表单"dbengine"的option选项的值为Aria，再提交安装下一步，应该可行的！
