### ISSUE TITLE
zblog新手有个tag查询疑问

### ISSUE THREAD

**Issue by suktec** [zblogcn/zblogphp#329]
$list_template = $tag->Template;
$w[] = array('LIKE', 'log_Tag', '%{' . $tag->ID . '}%'); 
//为什么这里用的是like查询，是因为$tag->ID会出现除整数外的其他类型值吗？
$pagebar->UrlRule->Rules['{%id%}'] = $tag->ID;
$pagebar->UrlRule->Rules['{%alias%}'] = $tag->Alias == '' ? rawurlencode($tag->Name) : $tag->Alias;
$pagebar->UrlRule->RulesObject = $tag;

**Comment by rainbowsoft** [comment]
因为没有post_tags关系表，而是存进了post表里，只能这样操作了。
