### ISSUE TITLE
为什么在安装BLOG程序的时候没有PGSQL选项啊

### ISSUE THREAD

**Issue by wbflike** [zblogcn/zblogphp#331]
为什么在安装BLOG程序的时候没有PGSQL选项啊

**Comment by wbflike** [comment]
![err](https://user-images.githubusercontent.com/22762921/157637283-fa5b85a1-10bc-45f2-8a16-bfb4aa20563a.png)
官网下载的最新版

**Comment by rainbowsoft** [comment]
php.ini extension=pdo_pgsql
