### ISSUE TITLE
FilterMember导致用户别名无法带*

### ISSUE THREAD

**Issue by mos1128** [zblogcn/zblogphp#339]
定位zb_system/function/c_system_function.php  
FilterMember方法中的$member->Alias = FormatString($member->Alias, '[normalname]');会导致Alias中有\*时被过滤。
而对于没有主动设置别名的用户来说，需要使用\*将账号脱敏作为别名

**Comment by zhouzishu** [comment]
用户数据中Name和Alias都是不允许「*」的出现的
如需脱敏，请通过 Member@__get() 中的接口人为修改输出结果
