### ISSUE TITLE
后台应用中心怎么没了

### ISSUE THREAD

**Issue by PR2176** [zblogcn/zblogphp#340]
![121.jpg](https://s2.loli.net/2023/01/04/fSrjhAw4ubPn1Yi.jpg)

**Comment by b41du** [comment]
you need to go to plugins page and activate app center plugin. if it also missing on plugins page, u can take it from new fresh installer of zblog located on /zb_users/plugin/
![image](https://user-images.githubusercontent.com/127647175/232266128-ee27cf65-90e5-4097-806c-0045b5cad64d.png)
you can paste that folder on your remote plugin folder.
