### ISSUE TITLE
侧栏模块的 FileName 转小写并无意义吧。。

### ISSUE THREAD

**Issue by wdssmq** [zblogcn/zblogphp#343]
zb_system/function/c_system_event.php#1829

```php
$_POST['FileName'] = strtolower($_POST['FileName']);
```

**Comment by imlgmcom** [comment]
难怪。我设置的文件名有个大写字母。结果调用不到





------------------ 原始邮件 ------------------
发件人: 沉冰浮水 ***@***.***&gt;
发送时间: 2023年5月16日 19:07
收件人: zblogcn/zblogphp ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zblogcn/zblogphp] 侧栏模块的 FileName 转小写并无意义吧。。 (Issue #343)





 
zb_system/function/c_system_event.php#1829
 $_POST['FileName'] = strtolower($_POST['FileName']);

**Comment by rainbowsoft** [comment]
当然有意义的，强制转小写可以避免很多麻烦。之前出问题的原因是不统一，现在已修正了。

**Comment by wdssmq** [comment]
> 当然有意义的，强制转小写可以避免很多麻烦。之前出问题的原因是不统一，现在已修正了。

所以查询时的兼容呢？所以 1.8 直接干掉 FileName 吧，用 mid 替代

**Comment by wdssmq** [comment]
`/^[a-zA-Z0-9_-]+$/` 正则限制一下就好。。
