### ISSUE TITLE
ZBLOG-PHP 1.7更换域名的问题

### ISSUE THREAD

**Issue by tanglu86** [zblogcn/zblogphp#344]
网站使用的老域名因为特殊原因不能继续使用了
目前新域名还在备案中
通过服务商给的临时域名访问后台地址发现CSS无法加载，后台验证也无法正常通过
请问这种情况如何挽救

**Comment by zhouzishu** [comment]
前往数据库找到 `%pre%_config`（zbp_config） 表，找到 `ZC_BLOG_HOST`，手动修改试试。
另外，非必要程序问题请前往 [https://bbs.zblogcn.com/](https://bbs.zblogcn.com) 发帖，无需在 GitHub 上提交 issue。

**Comment by wdssmq** [comment]
明确需要指定域名使用 - 常见问题 - 开始：

[https://docs.zblogcn.com/php/#/books/start-25-faq?id=%e6%98%8e%e7%a1%ae%e9%9c%80%e8%a6%81%e6%8c%87%e5%ae%9a%e5%9f%9f%e5%90%8d%e4%bd%bf%e7%94%a8](https://docs.zblogcn.com/php/#/books/start-25-faq?id=%e6%98%8e%e7%a1%ae%e9%9c%80%e8%a6%81%e6%8c%87%e5%ae%9a%e5%9f%9f%e5%90%8d%e4%bd%bf%e7%94%a8 "明确需要指定域名使用 - 常见问题 - 开始")
