### ISSUE TITLE
新安装的程序，使用Phpmyadmin导入的38W条数据出现异常

### ISSUE THREAD

**Issue by kexuebin** [zblogcn/zblogphp#353]
页面倒是能打开，但是明显有点慢。
后台有报错信息，大致是内存超过了，Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /www/wwwroot/www.aregbu.com/zb_system/function/lib/database/mysqli.php on line 245
但是同样的数据，同数据同服务器我在安装其它cms就没有这个内存耗尽的提示，请问一下这是什么原因导制的，感谢各位。

**Comment by kexuebin** [comment]
![微信图片_20231212094903](https://github.com/zblogcn/zblogphp/assets/20219652/cc0bdc11-4ea6-4c34-be83-0f777a7f8f1f)
导入254087条数据不会出现上面错误，254088条就要报错。

**Comment by wdssmq** [comment]
这是个「博客」定位的程序，以一天 1 篇讲，20 年下来是 `365 * 20 = 7300`
