### ISSUE TITLE
虚拟主机上 根目录安装的 会访问不了后台

### ISSUE THREAD

**Issue by imrelax** [zblogcn/zblogphp#356]
虚拟主机上 根目录安装的 会访问不了后台 会 403 错误。
但是只要移动到 二级目录就一切正常！
![ ](https://github.com/zblogcn/zblogphp/assets/33931868/1450ef64-1f27-4535-aac3-a19bb81fd55f)

如：www.***.com/zb_system/login.php   会 403
但是如果你把网站移动到 二级目录  www.***/aaa/zb_system/login.php  就可以正常访问。 
 
这个问题除了虚拟主机控权 比较严重之外。程序设计上是不是也有问题。导致这个问题！

**Comment by zhouzishu** [comment]
你尝试访问一下 `zb_system/api.php` 看看有没有类似问题

**Comment by imrelax** [comment]
![image](https://github.com/zblogcn/zblogphp/assets/33931868/5fdb96ff-78d9-4ebe-87c7-1d7a2416b658)

**Comment by imrelax** [comment]
访问 cmd.php 也会 403
访问 api.php 不会！

**Comment by zhouzishu** [comment]
请联系主机商，我并不认为是我们的程序设计问题，也无从查起。

**Comment by imrelax** [comment]
我测试了 另外一个虚拟主机。。 一样 还是 后台无法访问。 。
当然 宝塔等部署是没问题的。但是我尝试在虚拟主机下 部署 就发现 后台登录不上去。
/zb_system/cmd.php?act=login
 
![image](https://github.com/zblogcn/zblogphp/assets/33931868/3b6db949-cc27-4e1f-a17f-983b24cdcf1b)
