### ISSUE TITLE
你们对互联网标准太不尊重太不了解了

### ISSUE THREAD

**Issue by he110-c0de** [zblogcn/zblogphp#362]
最近用了一下zblog，发现你们只是一个20多年前单机时代码农的认知水平，还是传统软件思想方式。对互联网标准根本不懂也不重视。
希望你们好好学习进步。

**Comment by xfl12345** [comment]
希望大佬能对开源多做贡献，例如 fork 之后提交 Pull Request 。  
又或者开放一些开源仓库……

**Comment by LokiSharp** [comment]
什么是互联网标准？

**Comment by IntoTw** [comment]
🐢载着💈

**Comment by ossso** [comment]
所以，就来issue开炮吗？有问题怼论坛，怼猪都可以，但是issue就是这样被你们玩坏的。
