### ISSUE TITLE
将页面别名正则与文章页统一

### ISSUE THREAD

**Issue by wdssmq** [zblogcn/zblogphp#37]
区分对待意义不明。。。

\zb_system\function\lib\urlrule.php
 
160行

**Comment by zsxsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/2398785/15537816/0e2c9660-22ab-11e6-9c65-5374a0c3486d.png)
不知道哪个版本开始就已经统一了，懒得看Commit Log直接关了（
