### ISSUE TITLE
求增加ParseOrder功能...

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#38]
把sql里增加一个ParseOrder吧....  加入类似order by obj->Metas->XX  这种.... 反正也有ParseWhere了不是么....

**Comment by zsxsoft** [comment]
关联Issue: https://github.com/zblogcn/zblogphp/issues/79

**Comment by rainbowsoft** [comment]
关闭，这个是需要关系表的。

**Comment by birdol** [comment]
没找到reopen的按钮。。。擦。。。

**Comment by rainbowsoft** [comment]
已提交现实，正式关闭！💩💩💩
