### ISSUE TITLE
伪静态的bug？

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#39]
分类的链接规则设置为
{%host%}{%alias%}/{%page%}/
对应的iis6 下的伪静态规则是 
RewriteRule /(?:[^\./_]*)/(?!zb_)([^/]+)/(\?.*)? /index\.php\?alias=$1&rewrite=1 [I,L]

这前面的正则把css给匹配了... 导致css失效...

**Comment by zsxsoft** [comment]
什么CSS匹配了
