### ISSUE TITLE
错误提示友好化建议

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#48]
1、zbp->showerror的页面就不要给普通用户看了，很多人因为这个页面太丑，去吧error.html给改了，反而输出调试信息无法输出。普通用户给个alert信息，哪怕不准确，写个未知错误都行，真的，足够了。

2、安装插件或者主题的时候，如果是依赖插件，提示依赖ID，最好带上插件链接，这样就方便安装。如果是冲突插件，提示插件名字，最好带上禁用按钮，点一下就禁用了，很方便。

**Comment by zsxsoft** [comment]
第一点关于如何更友好的问题会进一步考虑
第二点明天开搞

**Comment by zsxsoft** [comment]
懒得搞了，让@zxasd 上……

**Comment by birdol** [comment]
@rainbowsoft 
#修复方式错误...麻烦重修...
所谓不友好值得是显示出那个showerror页面，很多人看到这个就去吧error.html改成404文件了。

普通用户给个简单的alert就行了，不要显示错误页面。

**Comment by zsxsoft** [comment]
现在把error.html改成了error.php，让他们不敢改。
不能用alert，必须错误页面。就这样。
