### ISSUE TITLE
ViewList函数完善

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#49]
case 'category':
	
			if (strpos($zbp->option['ZC_CATEGORY_REGEX'], '{%id%}') !== false) {
				$category = $zbp->GetCategoryByID($cate);
			}
			if (strpos($zbp->option['ZC_CATEGORY_REGEX'], '{%alias%}') !== false) {
				$category = $zbp->GetCategoryByAliasOrName($cate);
			}
改成在分类地址当中，使用了{$alias}时，只要GetCategoryByAliasOrID，不要用Name。

**Comment by birdol** [comment]
case 'tag':
……
			if (strpos($zbp->option['ZC_TAGS_REGEX'], '{%alias%}') !== false) {
				$tag = $zbp->GetTagByAliasOrName($tags);
			}
标签也建议一并修改。类似文章的UseIDnotName

**Comment by zsxsoft** [comment]
初步计划仅判断Alias。若Alias为空就使用Name或ID，这部分可能需要另行添加配置。
