### ISSUE TITLE
Filter_Plugin_Cmd_Ajax接口增加权限判定

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#62]
foreach ($GLOBALS['Filter_Plugin_Cmd_Ajax'] as $fpname => &$fpsignal) {
			$fpname(GetVars('src','GET'));
		}

改成
		foreach ($GLOBALS['Filter_Plugin_Cmd_Ajax'] as $fpname => &$fpsignal) {
^^^^^^^^^^^^^^^^^^^这里怎么写………………………………			$fpname(GetVars('src','GET')，$right);
		}

似乎没啥太大影响，以前老的插件也不影响使用。。。

优点就是。。。现在的方案每个src里面的函数都要单独判断权限...这样就不需要再写checkright了...

**Comment by zsxsoft** [comment]
没看懂要表达什么
