### ISSUE TITLE
app上传过大文件提醒

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#64]
一般主机默认上传是2M，后台插件管理，插件在上传的时候如果zba文件大小超过了这个限制没任何提示，导致用户摸不着头脑，建议加个提示。

**Comment by zsxsoft** [comment]
我怀疑可能没办法提示，只能检测上传的文件是否为空来看。
On Nov 8, 2015 16:21, birdol <notifications@github.com> wrote:一般主机默认上传是2M，后台插件管理，插件在上传的时候如果zba文件大小超过了这个限制没任何提示，导致用户摸不着头脑，建议加个提示。

**Comment by birdol** [comment]
好歹提示点什么吧。。。比如上传文件为空或者文件过大上传失败之类的，现在是完全静默，搞得好像是被上传的插件的问题。。。。
