### ISSUE TITLE
ParseWhere的一点bug。。。

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#66]
当整个sql语句中option同时包含pagebar和groupby参数的时候，由于pagebar的个数是通过
$s2 = $this->Count($table,array(array('COUNT','*','num')),$where);
这种方式查询计算出来的，但是整个语句由于groupby进行了合并，导致实际上的分页条没有那么多。

看看怎么处理吧。。。

**Comment by birdol** [comment]
提供一个暂时的解决办法：
不把pagebar作为option传给sql语句，然后输出pagebar之前判断一下页面数据，缺点是最后一页多一个按钮，优点就是，也就多一个按钮。。。
if(count($arrayinfo)>0){
$p->Count=$p->PageNow*$p->PageBarCount+1;//11;//按钮个数＝$p->PageBarCount*x＋1
}else{
$p->Count=$p->PageNow*$p->PageBarCount;//11;//按钮个数＝$p->PageBarCount*x＋1
    
}
$p->make();
－－－－－－－－－－－
坐等dbsql完善。

**Comment by rainbowsoft** [comment]
😡

在 2015年12月21日 下午1:02，birdol <notifications@github.com>写道：

> 提供一个暂时的解决办法：
> 不把pagebar作为option传给sql语句，然后输出pagebar之前判断一下页面数据，缺点是最后一页多一个按钮，优点就是，也就多一个按钮。。。
> if(count($arrayinfo)>0){
> $p->Count=$p->PageNow*$p->PageBarCount+1;//11;//按钮个数＝$p->PageBarCount*x＋1
> }else{
> $p->Count=$p->PageNow*$p->PageBarCount;//11;//按钮个数＝$p->PageBarCount*x＋1
>
> }
> $p->make();
> －－－－－－－－－－－
> 坐等dbsql完善。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zblogcn/zblogphp/issues/66#issuecomment-166203196>.
>



-- 
http://www.rainbowsoft.org/
