### ISSUE TITLE
同时查询两个数据表的时候，有bug。。。

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#67]
where语句如下：
    $wheretotal=array(
                        array('=', $zbp->table['myform_pro_info'].'.Form_ID', $form->ID),
                        array('=', $zbp->table['myform_pro_contents'].'.Form_ID', $form->ID),
                        array('=', $zbp->table['myform_pro_contents'].'.Info_ID', $zbp->table['myform_pro_info'].'.Info_ID')
                        );
世纪上操作起来ParseWhere中，把每个where的第三个参数给当作string处理了。
	                        $x = (string)$w[1];
				$y = (string)$w[2];
				$y = $this->db->EscapeString($y);
				$sqlw .= $comma . " $x $eq '$y' ";
现有解决方案只能是给where直接写成字符串，而不是数组，比如：
       $wheretotal=$zbp->option['ZC_MYSQL_PRE'].'myform_pro_info.Form_ID = '.$form->ID.' AND '.$zbp->option['ZC_MYSQL_PRE'].'myform_pro_contents.Form_ID = '.$form->ID.' AND '.$zbp->option['ZC_MYSQL_PRE'].'myform_pro_contents.Info_ID = '.$zbp->option['ZC_MYSQL_PRE'].'myform_pro_info.Info_ID';   

兼容性堪忧。。。毕竟咱不是只有mysql。。。还需要判断，好蛋疼。

**Comment by zsxsoft** [comment]
简化版：
```php
$where = [
['=', 'table1', '`table2`']
]
```
期待：

``WHERE table1 = table2``

实际：

``WHERE 'table1' = 'table2'``

**Comment by zsxsoft** [comment]
解决方案：
在下版本使用``->where(string)``来查询，如：``->where("zbp_comment.comm_logID = zbp_post.log_ID")``

你的例子直接写成
``
->where(array('=', $zbp->table['myform_pro_info'].'.Form_ID', $form->ID))
->where($zbp->option['ZC_MYSQL_PRE'].'myform_pro_contents.Form_ID = '.$form->ID)
->where($zbp->option['ZC_MYSQL_PRE'].'myform_pro_contents.Info_ID = '.$zbp->option['ZC_MYSQL_PRE'].'myform_pro_info.Info_ID)
``

嗯这个也不会造成数据库不兼容（
