### ISSUE TITLE
php版本的VerifyMessage cookie问题

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#69]
common.js中VerifyMessage这个函数。

在asp版本里是先保存访客留言的cookie，后ajax post，但是到了php版本里，如果ajaxpost失败或者产生了错误提示，就不保存cookie 了，这个太粗暴了吧？

**Comment by zsxsoft** [comment]
这很帅，不是么（笑

**Comment by birdol** [comment]
改啊改啊。。。

**Comment by involvements** [comment]
@birdol 不应该是这样吗？ajax失败基本上是昵称写错吧？
