### ISSUE TITLE
建议增加接口Filter_Plugin_Editor_Upload_SaveFile

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#74]
现状：只有upload类里面有一个接口：Filter_Plugin_Upload_SaveFile
问题：水印等插件通过Filter_Plugin_Upload_SaveFile来操作水印，导致zbp的所有插件，只要调用了$upload->SaveFile(),就会被打上水印。

建议方案：增加接口Filter_Plugin_Editor_Upload_SaveFile，并写到编辑器插件的upload文件里面，水印插件可以通过这里挂载，不影响其他插件自定义水印或者索性不要水印的操作。

**Comment by birdol** [comment]
类似的需求：
http://bbs.zblogcn.com/forum.php?mod=viewthread&tid=91463

**Comment by zsxsoft** [comment]
嗯，该加个，不过名字肯定没这么蠢。

**Comment by birdol** [comment]
哈哈，名字随意，快加快加。

**Comment by zsxsoft** [comment]
思考了一下，Upload类仅限于需要上传到zb_users/upload文件夹下的东西，也就是需要在附件管理里出现的东西。如果你的上传不需要被附件管理记录，为什么要用Upload类？

**Comment by birdol** [comment]
先不说我，就说上面论坛那个帖子的用户问题怎么解决吧。

用户希望文章上传的时候有水印。但是希望附件管理处上传没水印。

很多人不会整天开着ftp。可能还用不了kod。那就只能附件管理上传，然后主题编辑器修改文件。或者在模块管理里添加图片地址。结果被打了水印。。。

**Comment by zsxsoft** [comment]
这是水印插件作者该做的事情，他大可以在附件管理加个CheckBox决定要不要上传，或者只处理编辑器的上传。按你这个逻辑是不是每个上传的地方都要加接口了

**Comment by involvements** [comment]
的确可以分开检测，当然麻烦点

**Comment by birdol** [comment]
你们都赢了。。。我去写收费插件去- - 哇咔咔。。。
