### ISSUE TITLE
链式SQL调用

### ISSUE THREAD

**Issue by zsxsoft** [zblogcn/zblogphp#80]
我受不了傻逼的GetList了。

Except:
$zbp->sql->from("post")->where(array("=", "log_ID", "1"))->order(array("log_ViewNums", "DESC"))->sql

**Comment by involvements** [comment]
每次都得去复制

**Comment by zsxsoft** [comment]
Merged: https://github.com/zblogcn/zblogphp/commit/d70256d7e5b1af9b2a855085a174d8fb02ab43e1M
