### ISSUE TITLE
模板替换的小问题

### ISSUE THREAD

**Issue by kandytang** [zblogcn/zblogphp#82]
在模板中使用了`{$sth($str,array('a'=>'b'))}`，最后未能输出结果
查找原因在template.php第334行，只是简单的对“=”做了判断，将“=>”误判，故而没有最终编译成 `<? echo $sth($str,array('a'=>'b')) ?>`，导致结果无法输出
@zsxsoft @rainbowsoft 有劳尽快修复，谢谢！

**Comment by zsxsoft** [comment]
其实有的东西我倾向于直接写php代码来处理的，比如这种东西。那些标签只是提供简写方法而已。

这个我回头看看正则表达式，如果好处理的话就处理一下。

**Comment by kandytang** [comment]
模板化的原因就是为了简化开发，这个确实需要权衡，但是简单的多个一个判断对效率和代码量来说应该不是很大的损失：
`if(strpos($matches[1],'=')===false||strpos($matches[1],'=>')!==false){`

**Comment by kandytang** [comment]
另外当前的处理方法有两种：
一：
{$array=array('a'=>'b')}
{$sth($str,$array)}
二：
{php}echo {$sth($str,array('a'=>'b'))}{/php}
相对于修正后的标签：
{$sth($str,array('a'=>'b'))}
对模板开发者来说应该更简单，至少我对按照习惯这样去用标签却会出现无法输出结果的情况是很困惑的。
