### ISSUE TITLE
模板注释问题

### ISSUE THREAD

**Issue by rainbowsoft** [zblogcn/zblogphp#85]
{* 这里是注释 *}是会输出出来的，是否有一种不用输出的方式？

**Comment by rainbowsoft** [comment]
{// 这里是注释 }应该支持！

**Comment by zsxsoft** [comment]
注释输出个卵啊


Get Outlook for Android






On Tue, Jun 21, 2016 at 1:07 AM +0800, "zx.asd" <notifications@github.com> wrote:





{// 这里是注释 }应该支持！

---

**Comment by zsxsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/2398785/16214201/9984c740-3788-11e6-97eb-f36f11293c1b.png)

输出个P啊

**Comment by ossso** [comment]
卧槽，很有必要啊，给模板文件打一个备注，而且可以通过备注控制显示

**Comment by zsxsoft** [comment]
@ossso 这里一直都有的
