### ISSUE TITLE
导航条有个不大不小的bug

### ISSUE THREAD

**Issue by rainbowsoft** [zblogcn/zblogphp#86]
1.5能修修不

就是把页面或者分类。加入到导航之后

如果再修改了伪静态规则

导航条内容不会自动变。

除非刻意去编辑页面。加入到导航条 off提交。。再on一次提交……

分类也类似

**Comment by birdol** [comment]
都懒成这样了吗……=_= 
------------------ 原始邮件 ------------------
发件人: "zx.asd"<notifications@github.com>
发送时间: 2016年6月21日(星期二) 凌晨1:01
收件人: "zblogcn/zblogphp"<zblogphp@noreply.github.com>;
主题: [zblogcn/zblogphp] 导航条有个不大不小的bug (#86)



1.5能修修不
 
就是把页面或者分类。加入到导航之后
 
如果再修改了伪静态规则
 
导航条内容不会自动变。
 
除非刻意去编辑页面。加入到导航条 off提交。。再on一次提交……
 
分类也类似
 
&mdash;

**Comment by zsxsoft** [comment]
据说已修复，@rainbowsoft 说的
