### ISSUE TITLE
error.html建议隐藏实际路径

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#88]
error.html建议隐藏实际路径

现在叫error.php了？

原来出错的时候，是显示实际地址\文件路径\文件名

希望改成相对地址或者用一个符号代替，或者索性不写
比如：
ZBP_PATH/路径/index.php 这样

**Comment by zsxsoft** [comment]
不打开调试模式不会显示实际路径，打开调试模式显示实际路径开发更方便

**Comment by birdol** [comment]
让我这种常年开调试的情何以堪。。。- -
