### ISSUE TITLE
模板可否提供一个 标签解析忽略功能

### ISSUE THREAD

**Issue by birdol** [zblogcn/zblogphp#93]
当js代码中大括号{}与模板的大括号{}揉在一起的时候，有时候会出错。

甚至有时候没有揉在一起的时候也会报错。。。so，能不能提供一组标签，标签内的内容按照普通html或者js处理，而不解析其中的内容。

类似smarty的{literal}{/literal}

**Comment by zsxsoft** [comment]
可，今晚加
