### ISSUE TITLE
关于1.5的系统ajax评论矛盾问题

### ISSUE THREAD

**Issue by ossso** [zblogcn/zblogphp#94]
zbp的评论处理是把返回的html直接$()处理成为jquery对象，但我现在遇到了一个矛盾；
例如：我在comment.php中，把单条评论直接放在了一个div中：
`<div>xxxxx</div>`
zbp的评论ajax返回的是
`<label>xxxxx</label><div>xxxxxx</div>`
这种就没办法处理成jquery对象了啊，能不能把label去掉呢？

**Comment by zsxsoft** [comment]
的确比较麻烦，但是现在系统内加一个div包裹可能导致其他问题。建议2.0处理。


![image](https://cloud.githubusercontent.com/assets/2398785/17555273/8ccb4980-5f41-11e6-952a-ee7739793a14.png)
另外jQuery的行为是返回一个数组，如果因为版本问题的话你自己也可以加一个<div>上去的。
