### ISSUE TITLE
推荐更换自带的验证码字体为思源字体

### ISSUE THREAD

**Issue by ossso** [zblogcn/zblogphp#97]
RT，
同时建议降低一些干扰

**Comment by zsxsoft** [comment]
你算算那个字体多大

**Comment by ossso** [comment]
英文的字体名称在Noto里面是什么，找半天都没找到；我测试的一个版本是203K（理论上纯英文字体应该没这么大）
博士你试一下；

**Comment by ossso** [comment]
NotoSans-Bold.ttf   这个是名字……确实没单独的链接

**Comment by zsxsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/2398785/18416013/6dc493c8-7839-11e6-9a50-464226a5cb43.png)

我们现在带的才49K……

**Comment by ossso** [comment]
好吧，是我表达有误；主要原因是自带验证码识别率太低了，建议降低干扰和更换更容易识别的等宽字体

**Comment by zsxsoft** [comment]
我已经换了啊


Get Outlook for Android






On Sun, Sep 11, 2016 at 5:36 PM +0800, "橙色阳光" <notifications@github.com> wrote:





好吧，是我表达有误；主要原因是自带验证码识别率太低了，建议降低干扰和更换更容易识别的等宽字体

**Comment by ossso** [comment]
好吧，我错了，我玩的1.4……
